# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausApp', '0003_delete_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='negotiationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileOne', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
