# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausApp', '0004_negotiationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationtable',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
